ALTER TABLE ratios DROP CONSTRAINT ratios_pkey;

ALTER TABLE ratios ADD COLUMN year INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ratios ADD COLUMN period VARCHAR(4) NOT NULL DEFAULT 'YEAR';

ALTER TABLE ratios ALTER COLUMN year DROP DEFAULT;
ALTER TABLE ratios ALTER COLUMN period DROP DEFAULT;

ALTER TABLE ratios ADD PRIMARY KEY (ticker, year, period);
