export { HeroSection } from "./HeroSection"
export { CTAButtons } from "./CTAButtons"
export { DetailedFeatures } from "./DetailedFeatures"
export { ObjectionsSection } from "./ObjectionsSection"
export { SocialProofSection } from "./SocialProofSection"
export { FAQSection } from "./FAQSection"
export { PricingSection } from "./PricingSection"
export { FinalCTASection } from "./FinalCTASection"
