// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecase "ai-service/internal/usecase"
)

// AIProvider is an autogenerated mock type for the AIProvider type
type AIProvider struct {
	mock.Mock
}

// AnalyzeWithPDF provides a mock function with given fields: ctx, pdfBytes, systemPrompt, model
func (_m *AIProvider) AnalyzeWithPDF(ctx context.Context, pdfBytes []byte, systemPrompt string, model entity.AIModel) (string, error) {
	ret := _m.Called(ctx, pdfBytes, systemPrompt, model)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeWithPDF")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, entity.AIModel) (string, error)); ok {
		return rf(ctx, pdfBytes, systemPrompt, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, entity.AIModel) string); ok {
		r0 = rf(ctx, pdfBytes, systemPrompt, model)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, entity.AIModel) error); ok {
		r1 = rf(ctx, pdfBytes, systemPrompt, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateText provides a mock function with given fields: ctx, prompt, model, params
func (_m *AIProvider) GenerateText(ctx context.Context, prompt string, model entity.AIModel, params usecase.GenerateParams) (string, error) {
	ret := _m.Called(ctx, prompt, model, params)

	if len(ret) == 0 {
		panic("no return value specified for GenerateText")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.AIModel, usecase.GenerateParams) (string, error)); ok {
		return rf(ctx, prompt, model, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.AIModel, usecase.GenerateParams) string); ok {
		r0 = rf(ctx, prompt, model, params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.AIModel, usecase.GenerateParams) error); ok {
		r1 = rf(ctx, prompt, model, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIProvider creates a new instance of AIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIProvider {
	mock := &AIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
