// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DCFResultsRepository is an autogenerated mock type for the DCFResultsRepository type
type DCFResultsRepository struct {
	mock.Mock
}

// GetDCFResults provides a mock function with given fields: ctx, ticker
func (_m *DCFResultsRepository) GetDCFResults(ctx context.Context, ticker string) (*entity.DCFResult, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetDCFResults")
	}

	var r0 *entity.DCFResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.DCFResult, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.DCFResult); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DCFResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDCFResults provides a mock function with given fields: ctx, ticker, result
func (_m *DCFResultsRepository) SaveDCFResults(ctx context.Context, ticker string, result entity.DCFResult) error {
	ret := _m.Called(ctx, ticker, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveDCFResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.DCFResult) error); ok {
		r0 = rf(ctx, ticker, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDCFResultsRepository creates a new instance of DCFResultsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDCFResultsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DCFResultsRepository {
	mock := &DCFResultsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
