// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FinancialDataGateway is an autogenerated mock type for the FinancialDataGateway type
type FinancialDataGateway struct {
	mock.Mock
}

// GetCBRates provides a mock function with given fields: ctx
func (_m *FinancialDataGateway) GetCBRates(ctx context.Context) (*entity.CBRate, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCBRates")
	}

	var r0 *entity.CBRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.CBRate, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.CBRate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CBRate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyPrices provides a mock function with given fields: ctx, ticker
func (_m *FinancialDataGateway) GetDailyPrices(ctx context.Context, ticker string) ([]entity.Candle, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyPrices")
	}

	var r0 []entity.Candle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Candle, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Candle); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Candle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarketCap provides a mock function with given fields: ctx, ticker
func (_m *FinancialDataGateway) GetMarketCap(ctx context.Context, ticker string) (float64, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetMarketCap")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, ticker)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPriceAt provides a mock function with given fields: ctx, ticker, date
func (_m *FinancialDataGateway) GetPriceAt(ctx context.Context, ticker string, date time.Time) (float64, error) {
	ret := _m.Called(ctx, ticker, date)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceAt")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (float64, error)); ok {
		return rf(ctx, ticker, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) float64); ok {
		r0 = rf(ctx, ticker, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, ticker, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRawData provides a mock function with given fields: ctx, ticker, year, period
func (_m *FinancialDataGateway) GetRawData(ctx context.Context, ticker string, year int, period entity.ReportPeriod) (*entity.RawData, error) {
	ret := _m.Called(ctx, ticker, year, period)

	if len(ret) == 0 {
		panic("no return value specified for GetRawData")
	}

	var r0 *entity.RawData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, entity.ReportPeriod) (*entity.RawData, error)); ok {
		return rf(ctx, ticker, year, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, entity.ReportPeriod) *entity.RawData); ok {
		r0 = rf(ctx, ticker, year, period)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RawData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, entity.ReportPeriod) error); ok {
		r1 = rf(ctx, ticker, year, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRawDataHistory provides a mock function with given fields: ctx, ticker
func (_m *FinancialDataGateway) GetRawDataHistory(ctx context.Context, ticker string) ([]entity.RawData, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetRawDataHistory")
	}

	var r0 []entity.RawData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.RawData, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.RawData); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RawData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockInfo provides a mock function with given fields: ctx, ticker
func (_m *FinancialDataGateway) GetStockInfo(ctx context.Context, ticker string) (*entity.StockInfo, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetStockInfo")
	}

	var r0 *entity.StockInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.StockInfo, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.StockInfo); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.StockInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDraft provides a mock function with given fields: ctx, rawData
func (_m *FinancialDataGateway) SaveDraft(ctx context.Context, rawData *entity.RawData) error {
	ret := _m.Called(ctx, rawData)

	if len(ret) == 0 {
		panic("no return value specified for SaveDraft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RawData) error); ok {
		r0 = rf(ctx, rawData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFinancialDataGateway creates a new instance of FinancialDataGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinancialDataGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinancialDataGateway {
	mock := &FinancialDataGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
