// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ParserGateway is an autogenerated mock type for the ParserGateway type
type ParserGateway struct {
	mock.Mock
}

// GetLatestReport provides a mock function with given fields: ctx, ticker
func (_m *ParserGateway) GetLatestReport(ctx context.Context, ticker string) (*entity.Report, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestReport")
	}

	var r0 *entity.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Report, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Report); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsLatestReport provides a mock function with given fields: ctx, ticker, year, periodMonths
func (_m *ParserGateway) IsLatestReport(ctx context.Context, ticker string, year int, periodMonths int) (bool, error) {
	ret := _m.Called(ctx, ticker, year, periodMonths)

	if len(ret) == 0 {
		panic("no return value specified for IsLatestReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (bool, error)); ok {
		return rf(ctx, ticker, year, periodMonths)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) bool); ok {
		r0 = rf(ctx, ticker, year, periodMonths)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, ticker, year, periodMonths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewParserGateway creates a new instance of ParserGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParserGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParserGateway {
	mock := &ParserGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
