// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RiskAndGrowthRepository is an autogenerated mock type for the RiskAndGrowthRepository type
type RiskAndGrowthRepository struct {
	mock.Mock
}

// GetFreshRiskAndGrowth provides a mock function with given fields: ctx, ticker, ttl
func (_m *RiskAndGrowthRepository) GetFreshRiskAndGrowth(ctx context.Context, ticker string, ttl time.Duration) (*entity.RiskAndGrowthResponse, error) {
	ret := _m.Called(ctx, ticker, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GetFreshRiskAndGrowth")
	}

	var r0 *entity.RiskAndGrowthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (*entity.RiskAndGrowthResponse, error)); ok {
		return rf(ctx, ticker, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) *entity.RiskAndGrowthResponse); ok {
		r0 = rf(ctx, ticker, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RiskAndGrowthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, ticker, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveRiskAndGrowth provides a mock function with given fields: ctx, response
func (_m *RiskAndGrowthRepository) SaveRiskAndGrowth(ctx context.Context, response *entity.RiskAndGrowthResponse) error {
	ret := _m.Called(ctx, response)

	if len(ret) == 0 {
		panic("no return value specified for SaveRiskAndGrowth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RiskAndGrowthResponse) error); ok {
		r0 = rf(ctx, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRiskAndGrowthRepository creates a new instance of RiskAndGrowthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskAndGrowthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskAndGrowthRepository {
	mock := &RiskAndGrowthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
