// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "ai-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ScenarioRepository is an autogenerated mock type for the ScenarioRepository type
type ScenarioRepository struct {
	mock.Mock
}

// GetScenariosByID provides a mock function with given fields: ctx, ticker, taskID
func (_m *ScenarioRepository) GetScenariosByID(ctx context.Context, ticker string, taskID string) ([]entity.Scenario, error) {
	ret := _m.Called(ctx, ticker, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetScenariosByID")
	}

	var r0 []entity.Scenario
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Scenario, error)); ok {
		return rf(ctx, ticker, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entity.Scenario); ok {
		r0 = rf(ctx, ticker, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Scenario)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ticker, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveScenarios provides a mock function with given fields: ctx, taskID, ticker, scenarios
func (_m *ScenarioRepository) SaveScenarios(ctx context.Context, taskID string, ticker string, scenarios []entity.Scenario) error {
	ret := _m.Called(ctx, taskID, ticker, scenarios)

	if len(ret) == 0 {
		panic("no return value specified for SaveScenarios")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []entity.Scenario) error); ok {
		r0 = rf(ctx, taskID, ticker, scenarios)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewScenarioRepository creates a new instance of ScenarioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScenarioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScenarioRepository {
	mock := &ScenarioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
